# Generated by Django 4.2.6 on 2023-10-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supermarketsale",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="supermarketsale",
            name="tax",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="supermarketsale",
            name="total",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="supermarketsale",
            name="unit_price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
