# Generated by Django 4.2.6 on 2023-10-14 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0002_supermarketsale_quantity_supermarketsale_tax_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supermarketsale",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="supermarketsale",
            name="tax",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="supermarketsale",
            name="total",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="supermarketsale",
            name="unit_price",
            field=models.FloatField(default=0),
        ),
    ]
