# Generated by Django 4.2.6 on 2023-10-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0003_supermarketsale_date_alter_supermarketsale_tax_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supermarketsale",
            name="time",
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="supermarketsale",
            name="invoice_id",
            field=models.CharField(max_length=12),
        ),
    ]
